name: CI/CD on IaC

on:
  workflow_dispatch:
  push:
    branches: 
      - "main"
    paths:
      - "ServerlessFacesAnalyzer.IaC/**"
  pull_request:
    branches: 
      - "main"
    paths:
      - "ServerlessFacesAnalyzer.IaC/**"
      
env: 
  BICEP_PROJECT_PATH: '${{ github.workspace }}/ServerlessFacesAnalyzer.IaC'
  BICEP_MAIN_TEMPLATE: 'main.bicep'
  BUILD_OUTPUT_PATH: '${{ github.workspace }}/build-artifacts'

  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build BICEP template
        uses: Azure/cli@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            publishfolder="${{ github.workspace }}/output"
            mkdir ${{ env.BUILD_OUTPUT_PATH }}
            cd ${{ env.BUILD_OUTPUT_PATH }}
            az bicep build --file ${{ env.BICEP_PROJECT_PATH }}/${{ env.BICEP_MAIN_TEMPLATE }} --outfile main.json
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: build_artifacts
          path: ${{ env.BUILD_OUTPUT_PATH }}
          if-no-files-found: error
